namespace LernTor.Core.Design;

/// <summary>
/// Die Designs, aus denen die Kinder wählen (docs/NAECHSTES-LEVEL-3.md, Schritt 3). Jede Palette
/// besteht den Kontrasttest (<see cref="DesignContrastRules"/>, geprüft in
/// <c>DesignThemeCatalogTests</c>).
///
/// <para><b>Lavendel</b> ist das bisherige Aussehen - mit drei Korrekturen, die der Kontrasttest
/// am 30.09.2026 verlangt hat: das alte Grün (#00B894) und Orange (#F39C12) erreichten auf Weiß
/// nur 2,5 bzw. 2,2 : 1, der gelbe Fokusring 1,5 : 1. Sie sind jetzt dunkler; die Hauptfarbe ist
/// eine Spur dunkler (#6C5CE7 → #6352E0), weil sie auf dem Hintergrund knapp unter 4,5 : 1 lag.
/// <c>Resources/Colors.xaml</c> enthält dieselben Werte (geprüft in <c>DesignThemeCatalogTests</c>).</para>
///
/// <para>Ids sind beim Profil gespeichert - nie umbenennen, nur anhängen.</para>
/// </summary>
public static class DesignThemeCatalog
{
    public const string DefaultId = "lavendel";

    /// <summary>Das dunkle Design für "abends automatisch dunkel" und "wie Windows".</summary>
    public const string DarkId = "nacht";

    public static IReadOnlyList<DesignTheme> All { get; } = new[]
    {
        new DesignTheme("lavendel", "💜", "Lavendel", "Lavanta",
            "Das vertraute LernTor-Lila.",
            "Alışık olduğun LernTor moru.",
            IsDark: false,
            new DesignPalette
            {
                Background = "#F5F6FA",
                Surface = "#FFFFFF",
                TextPrimary = "#2D3436",
                TextSecondary = "#5F6A6E",
                Primary = "#6352E0",
                PrimaryDark = "#4834D4",
                OnColor = "#FFFFFF",
                Accent = "#FDCB6E",
                Focus = "#B9770E",
                Success = "#00806A",
                Error = "#C0392B",
                TileLavender = "#EDEAFB",
                TileSand = "#FEF3DC",
                TileMint = "#DFF7F0",
                TileRose = "#FDEAF2",
                ProgressTrack = "#E4E6F0",
                InputBorder = "#DDE1EA",
                Math = "#0984E3",
                German = "#6352E0",
                Turkish = "#D63384",
                Science = "#00806A",
                News = "#B9770E",
            }),
        new DesignTheme("ozean", "🌊", "Ozean", "Okyanus",
            "Blau und Türkis wie das Meer.",
            "Deniz gibi mavi ve turkuaz.",
            IsDark: false,
            new DesignPalette
            {
                Background = "#F0F7FA",
                Surface = "#FFFFFF",
                TextPrimary = "#16324F",
                TextSecondary = "#4A6378",
                Primary = "#0A6FA8",
                PrimaryDark = "#075985",
                OnColor = "#FFFFFF",
                Accent = "#BDE8F5",
                Focus = "#0E7490",
                Success = "#047857",
                Error = "#B42318",
                TileLavender = "#E0F2FE",
                TileSand = "#FEF6D8",
                TileMint = "#D8F5EA",
                TileRose = "#FCE7F3",
                ProgressTrack = "#DDE9F0",
                InputBorder = "#CBDDE8",
                Math = "#0369A1",
                German = "#6D28D9",
                Turkish = "#BE185D",
                Science = "#047857",
                News = "#B45309",
            }),
        new DesignTheme("wald", "🌲", "Wald", "Orman",
            "Ruhiges Grün.",
            "Sakin yeşil tonlar.",
            IsDark: false,
            new DesignPalette
            {
                Background = "#F3F7F2",
                Surface = "#FFFFFF",
                TextPrimary = "#1F2D1F",
                TextSecondary = "#4D5E4D",
                Primary = "#2E7031",
                PrimaryDark = "#1B5E20",
                OnColor = "#FFFFFF",
                Accent = "#E3F0C0",
                Focus = "#8A6D1F",
                Success = "#166534",
                Error = "#B3261E",
                TileLavender = "#E8F0E3",
                TileSand = "#F6EFD9",
                TileMint = "#DDF3E4",
                TileRose = "#F7E6E6",
                ProgressTrack = "#E1EADF",
                InputBorder = "#CCD9C9",
                Math = "#1D6FA3",
                German = "#6B4FA0",
                Turkish = "#B8336A",
                Science = "#2E7031",
                News = "#A65F00",
            }),
        new DesignTheme("sonnenuntergang", "🌅", "Sonnenuntergang", "Gün batımı",
            "Warmes Orange und Koralle.",
            "Sıcak turuncu ve mercan.",
            IsDark: false,
            new DesignPalette
            {
                Background = "#FFF6F0",
                Surface = "#FFFFFF",
                TextPrimary = "#3B2320",
                TextSecondary = "#6E4E47",
                Primary = "#C2410C",
                PrimaryDark = "#9A3412",
                OnColor = "#FFFFFF",
                Accent = "#FFE0B2",
                Focus = "#B45309",
                Success = "#15803D",
                Error = "#B91C1C",
                TileLavender = "#FDE7DC",
                TileSand = "#FFF1CC",
                TileMint = "#E3F5E9",
                TileRose = "#FCE4EC",
                ProgressTrack = "#F3E3DA",
                InputBorder = "#E8D2C6",
                Math = "#1D4ED8",
                German = "#7C3AED",
                Turkish = "#BE185D",
                Science = "#15803D",
                News = "#B45309",
            }),
        new DesignTheme("bonbon", "🍬", "Bonbon", "Şeker",
            "Rosa und Mint, verspielt.",
            "Pembe ve nane yeşili, eğlenceli.",
            IsDark: false,
            new DesignPalette
            {
                Background = "#FFF5FA",
                Surface = "#FFFFFF",
                TextPrimary = "#3A2340",
                TextSecondary = "#6B5070",
                Primary = "#C2185B",
                PrimaryDark = "#9C1450",
                OnColor = "#FFFFFF",
                Accent = "#C8F7E6",
                Focus = "#0F766E",
                Success = "#0F766E",
                Error = "#B42318",
                TileLavender = "#FCE4F1",
                TileSand = "#FFF3D6",
                TileMint = "#D9F7EC",
                TileRose = "#E9E3FB",
                ProgressTrack = "#F2E1EA",
                InputBorder = "#E6CFDB",
                Math = "#1565C0",
                German = "#6A1B9A",
                Turkish = "#AD1457",
                Science = "#00796B",
                News = "#B45309",
            }),
        new DesignTheme("nacht", "🌙", "Nacht", "Gece",
            "Dunkel und augenschonend für den Abend.",
            "Akşam için koyu ve gözü yormayan.",
            IsDark: true,
            new DesignPalette
            {
                Background = "#121826",
                Surface = "#1E2638",
                TextPrimary = "#E8ECF4",
                TextSecondary = "#AAB4C8",
                Primary = "#8E9BFF",
                PrimaryDark = "#B4BDFF",
                OnColor = "#0B1020",
                Accent = "#4A3F1C",
                Focus = "#FACC15",
                Success = "#4ADE80",
                Error = "#FF8A80",
                TileLavender = "#262B4A",
                TileSand = "#3A321E",
                TileMint = "#183A33",
                TileRose = "#3A2233",
                ProgressTrack = "#2A3348",
                InputBorder = "#3A4460",
                Math = "#60A5FA",
                German = "#A78BFA",
                Turkish = "#F472B6",
                Science = "#4ADE80",
                News = "#FBBF24",
            }),
        new DesignTheme("kontrast", "🔲", "Hoher Kontrast", "Yüksek kontrast",
            "Schwarz, Weiß und Gelb - am besten lesbar.",
            "Siyah, beyaz ve sarı - en kolay okunan.",
            IsDark: true,
            new DesignPalette
            {
                Background = "#000000",
                Surface = "#111111",
                TextPrimary = "#FFFFFF",
                TextSecondary = "#E0E0E0",
                Primary = "#FFE500",
                PrimaryDark = "#FFFFFF",
                OnColor = "#000000",
                Accent = "#3D3A00",
                Focus = "#00FFFF",
                Success = "#3DFF6E",
                Error = "#FF7B7B",
                TileLavender = "#1A1A2E",
                TileSand = "#1F1C00",
                TileMint = "#002218",
                TileRose = "#260016",
                ProgressTrack = "#333333",
                InputBorder = "#FFFFFF",
                Math = "#6CB4FF",
                German = "#D7A6FF",
                Turkish = "#FF8FD0",
                Science = "#3DFF6E",
                News = "#FFD166",
            }),
        new DesignTheme("galaxie", "🌌", "Galaxie", "Galaksi",
            "Dunkles Violett mit Gold - für echte Lernprofis.",
            "Altın detaylı koyu mor - gerçek öğrenme ustaları için.",
            IsDark: true,
            new DesignPalette
            {
                Background = "#0F0B1E",
                Surface = "#1C1733",
                TextPrimary = "#F1EDFF",
                TextSecondary = "#B9B0D9",
                Primary = "#C4A2FF",
                PrimaryDark = "#D8C4FF",
                OnColor = "#120C24",
                Accent = "#3B2F12",
                Focus = "#F5C84C",
                Success = "#5EEAD4",
                Error = "#FF8FA3",
                TileLavender = "#2A2146",
                TileSand = "#3A3016",
                TileMint = "#16343A",
                TileRose = "#3A1A34",
                ProgressTrack = "#2B2447",
                InputBorder = "#3E3566",
                Math = "#7DD3FC",
                German = "#C4B5FD",
                Turkish = "#F9A8D4",
                Science = "#5EEAD4",
                News = "#F5C84C",
            }, UnlockAchievementId: "lerntage-10"),
    };

    public static DesignTheme Default => All[0];

    /// <summary>Das Design mit dieser Id, sonst Lavendel - eine unbekannte Id (etwa aus einer
    /// neueren Version, deren Sicherung zurückgespielt wurde) darf nichts kaputt machen.</summary>
    public static DesignTheme Find(string? id) =>
        All.FirstOrDefault(t => string.Equals(t.Id, id, StringComparison.Ordinal)) ?? Default;
}
