using LernTor.Core.Enums;

namespace LernTor.ContentGen.Curriculum;

/// <summary>Doppeljahrgangsstufe des Berliner Rahmenlehrplans 1–10.</summary>
public enum RlpStufe
{
    Stufe5_6,
    Stufe7_8,
    Stufe9_10
}

public enum RlpStatus
{
    /// <summary>Mindestens ein Thema übt das Themenfeld.</summary>
    Abgedeckt,

    /// <summary>Themen üben einen Teil davon; <see cref="RlpThemenfeld.Hinweis"/> sagt, was fehlt.</summary>
    Teilweise,

    /// <summary>Noch kein Thema - eine Lücke, die geschlossen werden soll.</summary>
    Offen,

    /// <summary>Lässt sich nicht als Quizfrage üben (Sport, Arbeit am Rechner, Gestaltungspraxis).</summary>
    NichtAlsQuiz,

    /// <summary>Fach gibt es in LernTor nicht, weil es auf keinem Stundenplan der Familie steht.</summary>
    NichtInLernTor
}

/// <summary>Ein Thema eines Generators (Name der Themen-Methode in <c>TopicsByGrade</c>).</summary>
public sealed record RlpZuordnung(Subject Fach, string Thema);

/// <summary>Ein Themenfeld des Rahmenlehrplans und die Themen, die es in LernTor üben.</summary>
public sealed record RlpThemenfeld(
    RlpStufe Stufe,
    string Fach,
    string Titel,
    RlpStatus Status,
    IReadOnlyList<RlpZuordnung> Themen,
    string? Hinweis = null,
    string Quelle = RahmenlehrplanKatalog.QuelleFamilienDokument);

/// <summary>
/// Alle Themenfelder des Berliner Rahmenlehrplans 1–10, die LernTor kennt, mit ihrer Zuordnung zu
/// den Themen der Generatoren (docs/NAECHSTES-LEVEL-3-2.md, Schritt 1). Die einzige Stelle, die
/// sagt, welcher Teil des Rahmenlehrplans geübt wird: <c>RahmenlehrplanAbdeckungTests</c> prüft
/// jede Zuordnung gegen die Generatoren, und <c>docs/RAHMENLEHRPLAN.md</c> wird daraus erzeugt.
///
/// <para><b>Neues Thema in einem Generator? Hier eintragen,</b> beim passenden Themenfeld.</para>
/// </summary>
public static class RahmenlehrplanKatalog
{
    /// <summary>Quelle der Einträge 5/6 und 9/10: die Checklisten aus dem Familien-Dokument
    /// „LernTor Native – vollständiger und lückenloser Rahmenlehrplan Berlin“ und der Broschüre
    /// „Rahmenlehrplan 1–10 kompakt“ (2017), bisher in docs/CURRICULUM.md.</summary>
    public const string QuelleFamilienDokument = "Familien-Dokument + RLP kompakt 2017";

    public static IReadOnlyList<RlpThemenfeld> Alle { get; } = new RlpThemenfeld[]
    {
        new(RlpStufe.Stufe5_6, "Deutsch", "Vertiefung von Lese-/Schreibstrategien sowie sicheres Anwenden von Rechtschreibregeln", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "GrossKleinschreibung"), new(Subject.Deutsch, "AdjektivSteigerung") }),
        new(RlpStufe.Stufe5_6, "Deutsch", "Literarische Texte: Balladen sowie Kinder- und Jugendbücher", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "Balladen") }),
        new(RlpStufe.Stufe5_6, "Deutsch", "Sach- und Gebrauchstexte: Interviews, Zeitungsartikel, Grafiken auswerten", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "SachtexteAuswerten") }),
        new(RlpStufe.Stufe5_6, "Deutsch", "Texte in anderer medialer Form: Infosendungen, TV-Serien, Wikis, E-Mails", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "MedialeTexte") }),
        new(RlpStufe.Stufe5_6, "Deutsch", "Schreibformen: Schreibplan, formelle Briefe, Erzählungen, Berichte, Lesetagebücher, Parallelgedichte", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "Schreibformen") }),
        new(RlpStufe.Stufe5_6, "Deutsch", "Gesprächsformen/Redebeiträge: Diskussionen, Interviews, Präsentationen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "Gespraechsformen") }),
        new(RlpStufe.Stufe5_6, "Deutsch", "Struktur und Wirkung von Sprache: Wortarten, Satzarten, Wortbildung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "Wortarten"), new(Subject.Deutsch, "Satzarten"), new(Subject.Deutsch, "Wortbildung") }),
        new(RlpStufe.Stufe5_6, "Mathematik", "2.1 Zahlen und Operationen (Bruch-/Dezimalrechnung)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "BruchAddition"), new(Subject.Mathematik, "BruchMultiplikation"), new(Subject.Mathematik, "BruchDezimalUmwandlung") }),
        new(RlpStufe.Stufe5_6, "Mathematik", "2.2 Größen und Messen (Flächeninhalt/Volumen, Rechtecke/Quader)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "RechteckFlaeche"), new(Subject.Mathematik, "QuaderVolumen") }),
        new(RlpStufe.Stufe5_6, "Mathematik", "2.3 Raum und Form (Kongruenzabbildungen)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "Kongruenzabbildungen") }),
        new(RlpStufe.Stufe5_6, "Mathematik", "2.4 Gleichungen und Funktionen (Terme, proportionale Zuordnungen)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "ProportionaleZuordnung") }),
        new(RlpStufe.Stufe5_6, "Mathematik", "2.5 Daten und Zufall (Kombinatorik, relative Häufigkeit)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "Kombinatorik"), new(Subject.Mathematik, "WahrscheinlichkeitWuerfel") }),
        new(RlpStufe.Stufe5_6, "Englisch", "Themenfeld 1: Individuum und Lebenswelt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "AlltagUndFamilie") }),
        new(RlpStufe.Stufe5_6, "Englisch", "Themenfeld 2: Gesellschaft und öffentliches Leben", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "SchuleUndGesellschaft") }),
        new(RlpStufe.Stufe5_6, "Englisch", "Themenfeld 3: Kultur und historischer Hintergrund", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "KulturUndTraditionen") }),
        new(RlpStufe.Stufe5_6, "Englisch", "Themenfeld 4: Natur und Umwelt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "NaturUndUmwelt") }),
        new(RlpStufe.Stufe5_6, "Englisch", "Sprachliche Mittel: Grammatik", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "SimplePastFormen"), new(Subject.Englisch, "PossessivUndObjektpronomen"), new(Subject.Englisch, "PraepositionenInOnAt") }),
        new(RlpStufe.Stufe5_6, "Türkisch", "Themenfeld 1: Individuum und Lebenswelt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "AileVeGunlukYasam") }),
        new(RlpStufe.Stufe5_6, "Türkisch", "Themenfeld 2: Gesellschaft und öffentliches Leben", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "OkulVeToplum") }),
        new(RlpStufe.Stufe5_6, "Türkisch", "Themenfeld 3: Kultur und historischer Hintergrund", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "TurkiyeKulturu") }),
        new(RlpStufe.Stufe5_6, "Türkisch", "Themenfeld 4: Natur und Umwelt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "DogaVeCevre") }),
        new(RlpStufe.Stufe5_6, "Naturwissenschaften 5/6", "3.1 Von den Sinnen zum Messen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "MessenUndSinne") }),
        new(RlpStufe.Stufe5_6, "Naturwissenschaften 5/6", "3.2 Stoffe im Alltag", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "StoffeImAlltag") }),
        new(RlpStufe.Stufe5_6, "Naturwissenschaften 5/6", "3.3 Die Sonne als Energiequelle (Wasserkreislauf, Treibhauseffekt-Modell)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "SonneAlsEnergiequelle") }),
        new(RlpStufe.Stufe5_6, "Naturwissenschaften 5/6", "3.4 Welt des Großen – Welt des Kleinen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "OptikUndWeltraum") }),
        new(RlpStufe.Stufe5_6, "Naturwissenschaften 5/6", "3.5 Pflanzen – Tiere – Lebensräume (Winterschlaf, Frühblüher, Verbreitungsstrategien)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "Bluetenpflanzen"), new(Subject.Biologie, "LebensraeumeUndNahrungsketten"), new(Subject.Biologie, "UeberwinternVonTierenUndPflanzen") }),
        new(RlpStufe.Stufe5_6, "Naturwissenschaften 5/6", "3.6 Bewegung zu Wasser, zu Lande und in der Luft (Bionik)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "BewegungUndBionik") }),
        new(RlpStufe.Stufe5_6, "Naturwissenschaften 5/6", "3.7 Körper und Gesundheit (Ernährungspyramide, Suchtprävention explizit)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "ErnaehrungUndVerdauung"), new(Subject.Biologie, "GesundLebenUndSucht") }),
        new(RlpStufe.Stufe5_6, "Naturwissenschaften 5/6", "3.8 Sexualerziehung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "PubertaetUndEntwicklung") }),
        new(RlpStufe.Stufe5_6, "Naturwissenschaften 5/6", "3.9 Technik (einfacher Stromkreis, Leiter/Nichtleiter)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "Stromkreis") }),
        new(RlpStufe.Stufe5_6, "Gesellschaftswissenschaften 5/6 (Gewi)", "3.1 Ernährung – wie werden Menschen satt?", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Gewi, "Ernaehrung") }),
        new(RlpStufe.Stufe5_6, "Gesellschaftswissenschaften 5/6 (Gewi)", "3.2 Wasser – nur Natur oder in Menschenhand?", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Gewi, "WasserAlsRessource") }),
        new(RlpStufe.Stufe5_6, "Gesellschaftswissenschaften 5/6 (Gewi)", "3.3 Stadt und städtische Vielfalt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Gewi, "StadtUndVielfalt") }),
        new(RlpStufe.Stufe5_6, "Gesellschaftswissenschaften 5/6 (Gewi)", "3.4 Europa – grenzenlos?", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Gewi, "EuropaGrenzenlos") }),
        new(RlpStufe.Stufe5_6, "Gesellschaftswissenschaften 5/6 (Gewi)", "3.5 Tourismus und Mobilität", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Gewi, "TourismusUndMobilitaet") }),
        new(RlpStufe.Stufe5_6, "Gesellschaftswissenschaften 5/6 (Gewi)", "3.6 Demokratie und Mitbestimmung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Gewi, "DemokratieUndMitbestimmung") }),
        new(RlpStufe.Stufe5_6, "Biologie", "3.1 Die Zelle – kleinste Funktionseinheit des Lebendigen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "Zelle") }),
        new(RlpStufe.Stufe5_6, "Biologie", "3.2 Lebensräume und ihre Bewohner (Nahrungsketten)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "LebensraeumeUndNahrungsketten") }),
        new(RlpStufe.Stufe5_6, "Biologie", "3.3 Stoffwechsel des Menschen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "MenschlicheOrgane") }),
        new(RlpStufe.Stufe5_6, "Biologie", "3.4 Sexualität, Fortpflanzung und Entwicklung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "PubertaetUndEntwicklung") }),
        new(RlpStufe.Stufe5_6, "Chemie", "3.1 Faszination Chemie – Feuer, Schall und Rauch", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "Verbrennung") }),
        new(RlpStufe.Stufe5_6, "Chemie", "3.2 Das Periodensystem der Elemente – Übersicht und Werkzeug (Klasse-6-Niveau)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "PeriodensystemGrundlagen") }),
        new(RlpStufe.Stufe5_6, "Chemie", "3.3 Gase – zwischen lebensnotwendig und gefährlich", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "Gase") }),
        new(RlpStufe.Stufe5_6, "Chemie", "3.4 Wasser – eine Verbindung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "Wasser") }),
        new(RlpStufe.Stufe5_6, "Chemie", "3.5 Salze – Gegensätze ziehen sich an", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "Salze") }),
        new(RlpStufe.Stufe5_6, "Chemie", "3.6 Metalle – Schätze der Erde", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "MetalleEigenschaften") }),
        new(RlpStufe.Stufe5_6, "Physik", "3.1 Thermisches Verhalten von Körpern (Wärmeausdehnung)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "WaermeausdehnungKoerper") }),
        new(RlpStufe.Stufe5_6, "Physik", "3.2 Wechselwirkung und Kraft", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "WechselwirkungUndKraft") }),
        new(RlpStufe.Stufe5_6, "Physik", "3.3 Mechanische Energie und Arbeit", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "MechanischeEnergieUndArbeit") }),
        new(RlpStufe.Stufe5_6, "Physik", "3.4 Thermische Energie und Wärme", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "ThermischeEnergieUndWaerme") }),
        new(RlpStufe.Stufe5_6, "Geschichte", "3.1 Basismodule 7/8: Epochenüberblick (Mittelalter, Frühe Neuzeit, Revolutionen)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "Epochenueberblick") }),
        new(RlpStufe.Stufe5_6, "Geschichte", "3.2 Armut und Reichtum / Migrationen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "ArmutUndReichtumMigration") }),
        new(RlpStufe.Stufe5_6, "Geschichte", "3.3 Wahlmodule: z.B. Juden, Christen und Muslime", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "JudenChristenMuslime") }),
        new(RlpStufe.Stufe5_6, "Geografie", "3.1 Leben in Risikoräumen (Naturgefahren)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "RisikoraeumeNaturgefahren") }),
        new(RlpStufe.Stufe5_6, "Geografie", "3.2 Migration und Bevölkerung (Flucht, Landflucht)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "MigrationUndBevoelkerung") }),
        new(RlpStufe.Stufe5_6, "Geografie", "3.3 Vielfalt der Erde (tropischer Regenwald)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "TropischerRegenwald") }),
        new(RlpStufe.Stufe5_6, "Geografie", "3.4 Armut und Reichtum (Klasse-6-Niveau)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "ArmutUndReichtumKlasse6") }),
        new(RlpStufe.Stufe5_6, "Politische Bildung", "3.1 Armut und Reichtum (Klasse-6-Niveau)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "ArmutUndReichtumPolitik") }),
        new(RlpStufe.Stufe5_6, "Politische Bildung", "3.2 Leben in einer globalisierten Welt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "GlobalisierteWelt") }),
        new(RlpStufe.Stufe5_6, "Politische Bildung", "3.3 Migration und Bevölkerung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "MigrationPolitik") }),
        new(RlpStufe.Stufe5_6, "Politische Bildung", "3.4 Leben in einem Rechtsstaat (Klassenregeln, Jugendschutz, Kinderrechte)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "LebenImRechtsstaat") }),
        new(RlpStufe.Stufe5_6, "Ethik", "3.1 Wer bin ich? – Identität und Rolle", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "IdentitaetUndRolleKlasse6") }),
        new(RlpStufe.Stufe5_6, "Ethik", "3.2 Wie frei bin ich? – Freiheit und Verantwortung (Klasse-6-Niveau)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "FreiheitUndVerantwortungKlasse6") }),
        new(RlpStufe.Stufe5_6, "Ethik", "3.3 Was ist gerecht? – Recht und Gerechtigkeit (Klasse-6-Niveau)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "RechtUndGerechtigkeitKlasse6") }),
        new(RlpStufe.Stufe5_6, "Ethik", "3.4 Was ist der Mensch? – Mensch und Gemeinschaft (Toleranz, Konflikte)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "Freundschaft") }),
        new(RlpStufe.Stufe5_6, "Kunst", "14.1 Inhaltsbereich: Kunstwerke (Konzepte 5/6)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "KunstwerkeWahrnehmen") }),
        new(RlpStufe.Stufe5_6, "Kunst", "14.2 Inhaltsbereich: Material, Körper und Raum", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "MaterialKoerperRaum") }),
        new(RlpStufe.Stufe5_6, "Kunst", "14.3 Inhaltsbereich: Medien", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "MedienUndVerfahren") }),
        new(RlpStufe.Stufe5_6, "Kunst", "14.4 Inhaltsbereich: Individuelle Erfahrungen (Alltag und Lebenswelt)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "KunstUndLebenswelt") }),
        new(RlpStufe.Stufe5_6, "Kunst", "14.5 Inhaltsbereich: Verfahren und Werkzeuge (Gestaltungspraxis)", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Gestaltungspraxis mit Werkzeugen und Material."),
        new(RlpStufe.Stufe5_6, "Musik", "Themenfeld 1: Grundlagen der Musik", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "GrundlagenDerMusik") }),
        new(RlpStufe.Stufe5_6, "Musik", "Themenfeld 2: Form und Gestaltung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "FormUndGestaltung") }),
        new(RlpStufe.Stufe5_6, "Musik", "Themenfeld 3: Gattungen und Genres", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "GattungenUndGenres") }),
        new(RlpStufe.Stufe5_6, "Musik", "Themenfeld 4: Wirkung und Funktion", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "WirkungUndFunktion") }),
        new(RlpStufe.Stufe5_6, "Musik", "Themenfeld 5: Musik im kulturellen Kontext", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "MusikImKulturellenKontext") }),
        new(RlpStufe.Stufe5_6, "Musik", "Musik gestalten/Notation", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "NotenwerteUndTakt") }),
        new(RlpStufe.Stufe5_6, "Musik", "Stimme und Singen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "StimmeUndGesang") }),
        new(RlpStufe.Stufe5_6, "Sport", "16.1 Bewegungsfeld 1: Laufen, Springen, Werfen, Stoßen (Leichtathletik)", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe5_6, "Sport", "16.2 Bewegungsfeld 2: Spielen (Kleine Spiele & Sportspiele)", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe5_6, "Sport", "16.3 Bewegungsfeld 3: Bewegen an Geräten (Turnen & Parkour)", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe5_6, "Sport", "16.4 Optionales Bewegungsfeld: Kämpfen nach Regeln", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe5_6, "ITG", "Themenfeld: Standardsoftware", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Praktischer Umgang mit Textverarbeitung und Tabellenkalkulation am Rechner."),
        new(RlpStufe.Stufe5_6, "ITG", "Themenfeld: Informatiksysteme (Datenschutz-Grundlagen, sichere Passwörter)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Itg, "Datenschutz"), new(Subject.Itg, "SicherePasswoerter") }),
        new(RlpStufe.Stufe5_6, "ITG", "Themenfeld: Leben in und mit vernetzten Systemen (Urheberrecht)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Itg, "Urheberrecht") }),
        new(RlpStufe.Stufe9_10, "Deutsch", "1.1 Literarische Texte erschließen (Analyse & Interpretation)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "DramaAufbau"), new(Subject.Deutsch, "Figurencharakterisierung"), new(Subject.Deutsch, "Novelle"), new(Subject.Deutsch, "Parabel") }),
        new(RlpStufe.Stufe9_10, "Deutsch", "1.2 Sach- und Gebrauchstexte auswerten", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "Quellenkritik") }),
        new(RlpStufe.Stufe9_10, "Deutsch", "1.3 Texte in unterschiedlicher medialer Form (Filmanalyse)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "Filmanalyse") }),
        new(RlpStufe.Stufe9_10, "Deutsch", "1.4 Texte verfassen (Schreibformen & Argumentation)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "Textsorten"), new(Subject.Deutsch, "RedeUndBewerbung") }),
        new(RlpStufe.Stufe9_10, "Deutsch", "1.5 Gesprächsformen und Rhetorik (Mündlichkeit)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "RedeUndBewerbung") }),
        new(RlpStufe.Stufe9_10, "Deutsch", "1.6 Sprachwissen und Grammatik (Sprachbewusstheit)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Deutsch, "Satzbau"), new(Subject.Deutsch, "Wortbedeutung9"), new(Subject.Deutsch, "Konjunktionen"), new(Subject.Deutsch, "AktivPassiv"), new(Subject.Deutsch, "Kommasetzung"), new(Subject.Deutsch, "DassOderDas") }),
        new(RlpStufe.Stufe9_10, "Mathematik", "1. Zahlen und Operationen (reelle Zahlen, Potenzgesetze)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "Potenzgesetze") }),
        new(RlpStufe.Stufe9_10, "Mathematik", "2. Größen und Messen (Trigonometrie, Körperberechnungen)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "Trigonometrie"), new(Subject.Mathematik, "PyramideKegelKugelVolumen") }),
        new(RlpStufe.Stufe9_10, "Mathematik", "3. Raum und Form (Satz des Thales/Pythagoras)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "SatzDesThales"), new(Subject.Mathematik, "SatzDesPythagoras") }),
        new(RlpStufe.Stufe9_10, "Mathematik", "4. Gleichungen und Funktionen (LGS, quadratische/Exponentialfunktionen)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "LinearesGleichungssystem"), new(Subject.Mathematik, "QuadratischeFunktionMerkmale"), new(Subject.Mathematik, "Exponentialfunktion") }),
        new(RlpStufe.Stufe9_10, "Mathematik", "5. Daten und Zufall (Stochastik: mehrstufige Wahrscheinlichkeiten, Baumdiagramme)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "MehrstufigeZufallsversuche") }),
        new(RlpStufe.Stufe9_10, "Mathematik", "6. Wahlpflichtmodul A: Wachstumsprozesse", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Mathematik, "Exponentialfunktion") }),
        new(RlpStufe.Stufe9_10, "Mathematik", "7. Wahlpflichtmodul B: Darstellende Geometrie (Zweitafelprojektion)", RlpStatus.Offen,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflichtmodul; nur nötig, wenn die Schule es wählt."),
        new(RlpStufe.Stufe9_10, "Englisch", "3.1 Persönlichkeit, Identität und Zukunft", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "IdentitaetUndZukunft") }),
        new(RlpStufe.Stufe9_10, "Englisch", "3.2 Alltag, Konsum und Wohnwelt (Werbung, Verbraucherschutz)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "AlltagUndKonsum") }),
        new(RlpStufe.Stufe9_10, "Englisch", "3.3 Gesellschaftliches Zusammenleben und Medien", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "GesellschaftUndMedien") }),
        new(RlpStufe.Stufe9_10, "Englisch", "3.4 Schule, Ausbildung und Arbeitswelt (Bewerbung)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "SchuleUndArbeitswelt") }),
        new(RlpStufe.Stufe9_10, "Englisch", "3.5 Kultur und historischer Hintergrund (Klasse-9-Niveau)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "KulturUndHistorischerHintergrund") }),
        new(RlpStufe.Stufe9_10, "Englisch", "3.6 Natur, Umwelt und Ökologie", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "UmweltUndNachhaltigkeit") }),
        new(RlpStufe.Stufe9_10, "Englisch", "Sprachliche Mittel B1: Grammatik", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Englisch, "SecondConditional"), new(Subject.Englisch, "RelativeClauses") }),
        new(RlpStufe.Stufe9_10, "Türkisch", "4.1 Identität, Lebenswelt und Migration", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "KimlikVeGelecek") }),
        new(RlpStufe.Stufe9_10, "Türkisch", "4.2 Alltag, Konsum und türkische Kultur", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "AlltagUndKonsum") }),
        new(RlpStufe.Stufe9_10, "Türkisch", "4.3 Gesellschaft und öffentliches Leben (Klasse-9-Niveau)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "GesellschaftUndOeffentlichesLeben") }),
        new(RlpStufe.Stufe9_10, "Türkisch", "4.4 Schule, Ausbildung und Berufswelt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "SchuleUndBerufswelt") }),
        new(RlpStufe.Stufe9_10, "Türkisch", "4.5 Traditionen und historischer Hintergrund", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "TarihVeGelenekler") }),
        new(RlpStufe.Stufe9_10, "Türkisch", "4.6 Natur, Umwelt und Regionen der Türkei", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Tuerkisch, "TurkiyeCografyasi") }),
        new(RlpStufe.Stufe9_10, "Biologie", "5.1 Gesundheit und Krankheit (Infektionsbiologie & Immunologie)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "Immunsystem") }),
        new(RlpStufe.Stufe9_10, "Biologie", "5.2 Bau und Funktion des Nervensystems (Neurobiologie)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "Nervensystem") }),
        new(RlpStufe.Stufe9_10, "Biologie", "5.3 Sucht und Suchtprävention", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "SuchtUndSuchtpraevention") }),
        new(RlpStufe.Stufe9_10, "Biologie", "5.4 Zelluläre Grundlagen der Vererbung (Mitose/Meiose)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "Humangenetik") }),
        new(RlpStufe.Stufe9_10, "Biologie", "5.5 Vererbung beim Menschen (Humangenetik & Genmutationen)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "Humangenetik") }),
        new(RlpStufe.Stufe9_10, "Biologie", "5.6 Evolution – Theorien und Stammesgeschichte", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Biologie, "Evolution") }),
        new(RlpStufe.Stufe9_10, "Chemie", "6.1 Klare Verhältnisse – Quantitative Betrachtungen (Stöchiometrie)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "Stoechiometrie") }),
        new(RlpStufe.Stufe9_10, "Chemie", "6.2 Säuren und Laugen – echt ätzend", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "SaeureBaseVertieft") }),
        new(RlpStufe.Stufe9_10, "Chemie", "6.3 Kohlenwasserstoffe – vom Campinggas zum Superbenzin", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "Kohlenwasserstoffe") }),
        new(RlpStufe.Stufe9_10, "Chemie", "6.4 Alkohole – vom Holzgeist zum Glycerin", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "Alkohole") }),
        new(RlpStufe.Stufe9_10, "Chemie", "6.5 Organische Säuren – Salatsauce, Entkalker & Co", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "OrganischeSaeuren") }),
        new(RlpStufe.Stufe9_10, "Chemie", "6.6 Ester – Vielfalt der Produkte aus Alkoholen und Säuren", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Chemie, "Ester") }),
        new(RlpStufe.Stufe9_10, "Physik", "7.1 Gleichförmige und beschleunigte Bewegungen (Kinematik)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "Kinematik") }),
        new(RlpStufe.Stufe9_10, "Physik", "7.2 Kraft und Beschleunigung (Dynamik)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "NewtonscheGesetze") }),
        new(RlpStufe.Stufe9_10, "Physik", "7.3 Magnetfelder und elektromagnetische Induktion", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "MagnetfelderInduktion") }),
        new(RlpStufe.Stufe9_10, "Physik", "7.4 Radioaktivität und Kernphysik", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "RadioaktivitaetUndKernphysik") }),
        new(RlpStufe.Stufe9_10, "Physik", "7.5 Energieumwandlungen in Natur und Technik", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "Energieerhaltung") }),
        new(RlpStufe.Stufe9_10, "Physik", "7.6 Schwingungen, Wellen und Optische Geräte", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Physik, "SchwingungenWellenOptik") }),
        new(RlpStufe.Stufe9_10, "Geschichte", "8.1 Basismodul 1: Demokratie und Diktatur", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "DemokratieUndDiktatur") }),
        new(RlpStufe.Stufe9_10, "Geschichte", "8.2 Basismodul 2: Der Kalte Krieg und die geteilte Welt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "KalterKrieg") }),
        new(RlpStufe.Stufe9_10, "Geschichte", "8.3 Verbundmodul 1: Konflikte und Konfliktlösungen (Nahost-Fallanalyse)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "KonflikteUndKonfliktloesungen") }),
        new(RlpStufe.Stufe9_10, "Geschichte", "8.4 Verbundmodul 2: Europa in der Welt (globalhistorischer Vergleich)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "EuropaInDerWelt") }),
        new(RlpStufe.Stufe9_10, "Geschichte", "8.5 Wahlmodul-Fokus A: Völkermorde und Massengewalt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "VoelkermordeUndMassengewalt") }),
        new(RlpStufe.Stufe9_10, "Geschichte", "8.6 Wahlmodul-Fokus B: Die Welt nach dem Kalten Krieg (1989-1991)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "WeltNachDemKaltenKrieg") }),
        new(RlpStufe.Stufe9_10, "Geschichte", "8.7 (Bonus) Wahlmodul-Fokus C: Feindbilder und Propaganda", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geschichte, "FeindbilderUndPropaganda") }),
        new(RlpStufe.Stufe9_10, "Geografie", "9.1 Umgang mit Ressourcen: Energie und Rohstoffe", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "RessourcenEnergie") }),
        new(RlpStufe.Stufe9_10, "Geografie", "9.2 Umgang mit Ressourcen: Landwirtschaft und Boden", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "LandwirtschaftUndBoden") }),
        new(RlpStufe.Stufe9_10, "Geografie", "9.3 Das Klimasystem und der Klimawandel", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "Klimawandel") }),
        new(RlpStufe.Stufe9_10, "Geografie", "9.4 Klimaschutz: Internationale Konflikte und Lösungen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "KlimaschutzInternational") }),
        new(RlpStufe.Stufe9_10, "Geografie", "9.5 Wirtschaftliche Verflechtungen und Globalisierung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "WirtschaftlicheVerflechtung") }),
        new(RlpStufe.Stufe9_10, "Geografie", "9.6 Europa in der Welt (Verbundmodul)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Geo, "EuropaWirtschaftsraum") }),
        new(RlpStufe.Stufe9_10, "Politische Bildung", "10.1 Demokratie in Deutschland: Prinzipien und Institutionen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "Gewaltenteilung"), new(Subject.Politik, "BundestagBundesrat") }),
        new(RlpStufe.Stufe9_10, "Politische Bildung", "10.2 Demokratie in Deutschland: Willensbildung, Medien und Gefährdungen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "WillensbildungUndMedien") }),
        new(RlpStufe.Stufe9_10, "Politische Bildung", "10.3 Konflikte und Konfliktlösungen: internationale Akteure", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "KonflikteInternationaleAkteure") }),
        new(RlpStufe.Stufe9_10, "Politische Bildung", "10.4 Friedenssicherung und Entwicklungspolitik", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "FriedenssicherungUndEntwicklungspolitik") }),
        new(RlpStufe.Stufe9_10, "Politische Bildung", "10.5 Soziale Marktwirtschaft im Spannungsfeld", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "SozialeMarktwirtschaft") }),
        new(RlpStufe.Stufe9_10, "Politische Bildung", "10.6 Europa in der Welt: Die Europäische Union", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Politik, "EuropaeischeUnion") }),
        new(RlpStufe.Stufe9_10, "Ethik", "11.1 Wer bin ich? – Identität und Rolle (Kant/Autonomie, Gender)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "IdentitaetUndRolle") }),
        new(RlpStufe.Stufe9_10, "Ethik", "11.2 Wie frei bin ich? – Freiheit und Verantwortung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "Verantwortung"), new(Subject.Ethik, "FreiheitPhilosophisch") }),
        new(RlpStufe.Stufe9_10, "Ethik", "11.3 Was ist gerecht? – Recht und Gerechtigkeit", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "RechtUndGerechtigkeit"), new(Subject.Ethik, "GerechtigkeitstheorienVertieft") }),
        new(RlpStufe.Stufe9_10, "Ethik", "11.4 Was ist der Mensch? – Mensch und Gemeinschaft (Hobbes/Rousseau)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "MenschUndGemeinschaft") }),
        new(RlpStufe.Stufe9_10, "Ethik", "11.5 Was soll ich tun? – Handeln und Moral (Dilemmata, Pflichtethik/Utilitarismus)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "HandelnUndMoral") }),
        new(RlpStufe.Stufe9_10, "Ethik", "11.6 Worauf kann ich vertrauen? – Wissen und Glauben", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Ethik, "WissenUndGlauben") }),
        new(RlpStufe.Stufe9_10, "Kunst", "12.1 Kunst als Intervention und Mahnung", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "KunstAlsInterventionUndMahnung") }),
        new(RlpStufe.Stufe9_10, "Kunst", "12.2 Medienkunst und Bildhaftes Gestalten", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "MedienkunstUndBildhaftesGestalten") }),
        new(RlpStufe.Stufe9_10, "Kunst", "12.3 Architektur, Raum und Design", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "ArchitekturRaumUndDesign") }),
        new(RlpStufe.Stufe9_10, "Kunst", "12.4 Materialästhetik und Transformation", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "MaterialaesthetikUndTransformation") }),
        new(RlpStufe.Stufe9_10, "Kunst", "12.5 Inszenierung und Kuration", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "InszenierungUndKuration") }),
        new(RlpStufe.Stufe9_10, "Kunst", "12.6 Kulturelle Identität und Vielfalt", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Kunst, "KulturelleIdentitaetUndVielfalt") }),
        new(RlpStufe.Stufe9_10, "Musik", "13.1 Grundlagen der Musik: Harmonielehre und Partiturlesen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "HarmonielehreUndPartiturlesen") }),
        new(RlpStufe.Stufe9_10, "Musik", "13.2 Form und Gestaltung: Komposition und Satzweisen", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "KompositionUndSatzweisen") }),
        new(RlpStufe.Stufe9_10, "Musik", "13.3 Medien und digitale Produktion", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "MedienUndDigitaleProduktion") }),
        new(RlpStufe.Stufe9_10, "Musik", "13.4 Gattungen und Genres der Musikgeschichte", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "GattungenDerMusikgeschichte") }),
        new(RlpStufe.Stufe9_10, "Musik", "13.5 Wirkung und Funktion: Filmmusik und Programmmusik", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "FilmmusikUndProgrammmusik") }),
        new(RlpStufe.Stufe9_10, "Musik", "13.6 Musik im kulturellen und gesellschaftlichen Kontext", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Musik, "MusikImGesellschaftlichenKontext") }),
        new(RlpStufe.Stufe9_10, "Sport", "14.1 Laufen, Springen, Werfen (Leichtathletik & Biomechanik)", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe9_10, "Sport", "14.2 Spielen (Sportspiele & Taktik)", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe9_10, "Sport", "14.3 Bewegen an Geräten (Turnen & Parkour)", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe9_10, "Sport", "14.4 Kämpfen nach Regeln (Zweikampf & Fair Play)", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe9_10, "Sport", "14.5 Bewegungsfolgen gestalten (Tanz, Akrobatik, Rhythmus)", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe9_10, "Sport", "14.6 Trainingsmethodik und Fitness", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Sport lässt sich nicht als Quizfrage üben."),
        new(RlpStufe.Stufe9_10, "ITG", "Themenfeld: Standardsoftware", RlpStatus.NichtAlsQuiz,
            new RlpZuordnung[] {  }, Hinweis: "Praktischer Umgang mit Textverarbeitung und Tabellenkalkulation am Rechner."),
        new(RlpStufe.Stufe9_10, "ITG", "Themenfeld: Informatiksysteme", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Itg, "Informatiksysteme") }),
        new(RlpStufe.Stufe9_10, "ITG", "Themenfeld: Leben in und mit vernetzten Systemen (Cybermobbing, Fake News)", RlpStatus.Abgedeckt,
            new RlpZuordnung[] { new(Subject.Itg, "Cybermobbing"), new(Subject.Itg, "FakeNewsErkennen") }),
        new(RlpStufe.Stufe9_10, "Wirtschaft-Arbeit-Technik (WAT)", "16.1 Ernährung und Konsum aus regionaler und globaler Sicht (P9)", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Wirtschaft-Arbeit-Technik (WAT)", "16.2 Unternehmerisches Handeln (P10)", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Wirtschaft-Arbeit-Technik (WAT)", "16.3 Berufs- und Lebenswegplanung: Erkunden und Entscheiden (P11)", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Wirtschaft-Arbeit-Technik (WAT)", "16.4 Gestaltung komplexer Projekte und Technikbewertung (P12)", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Wirtschaft-Arbeit-Technik (WAT)", "16.5 Computergesteuerte Fertigung und Automatisierung (Wahlpflicht WP5)", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Wirtschaft-Arbeit-Technik (WAT)", "16.6 Mobilität und Energieversorgung der Zukunft (Wahlpflicht WP7)", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Naturwissenschaften (Wahlpflicht 7–10)", "17.1 Klima im Wandel", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Naturwissenschaften (Wahlpflicht 7–10)", "17.2 Energieversorgung der Menschheit", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Naturwissenschaften (Wahlpflicht 7–10)", "17.3 Kondensate zum Essen und Verpacken (Polymerchemie)", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Naturwissenschaften (Wahlpflicht 7–10)", "17.4 Nahrung für die Welt", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Naturwissenschaften (Wahlpflicht 7–10)", "17.5 Information und Kommunikation (Neurobiologie/Informatik)", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
        new(RlpStufe.Stufe9_10, "Naturwissenschaften (Wahlpflicht 7–10)", "17.6 Bauen, Wohnen und Bionik", RlpStatus.NichtInLernTor,
            new RlpZuordnung[] {  }, Hinweis: "Wahlpflicht; steht auf keinem der beiden Stundenpläne."),
    };
}
