<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>LernTor.News</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LernTor.Core\LernTor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Syndication" />
  </ItemGroup>

</Project>
